// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartButton_linx from "./islands/AddToCartButton/linx.tsx";
import * as $AddToCartButton_nuvemshop from "./islands/AddToCartButton/nuvemshop.tsx";
import * as $AddToCartButton_quantity from "./islands/AddToCartButton/quantity.tsx";
import * as $AddToCartButton_shopify from "./islands/AddToCartButton/shopify.tsx";
import * as $AddToCartButton_vnda from "./islands/AddToCartButton/vnda.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $AddToCartButton_vtexBTG from "./islands/AddToCartButton/vtexBTG.tsx";
import * as $AddToCartButton_vtexFloatingPDP from "./islands/AddToCartButton/vtexFloatingPDP.tsx";
import * as $AddToCartButton_vtexPDP from "./islands/AddToCartButton/vtexPDP.tsx";
import * as $AddToCartButton_wake from "./islands/AddToCartButton/wake.tsx";
import * as $BackToTop from "./islands/BackToTop.tsx";
import * as $ButtonCookies from "./islands/ButtonCookies.tsx";
import * as $CustomSort from "./islands/CustomSort.tsx";
import * as $EmptySearchParams from "./islands/EmptySearchParams.tsx";
import * as $FilterRangePrice from "./islands/FilterRangePrice.tsx";
import * as $Filters from "./islands/Filters.tsx";
import * as $FloatingBuyScroll from "./islands/FloatingBuyScroll.tsx";
import * as $FloatingDesktopHeaderPhytoSpa from "./islands/FloatingDesktopHeaderPhytoSpa.tsx";
import * as $FloatingMobileBar from "./islands/FloatingMobileBar.tsx";
import * as $Head from "./islands/Head.tsx";
import * as $Header_Buttons from "./islands/Header/Buttons.tsx";
import * as $Header_Cart_linx from "./islands/Header/Cart/linx.tsx";
import * as $Header_Cart_nuvemshop from "./islands/Header/Cart/nuvemshop.tsx";
import * as $Header_Cart_shopify from "./islands/Header/Cart/shopify.tsx";
import * as $Header_Cart_vnda from "./islands/Header/Cart/vnda.tsx";
import * as $Header_Cart_vtex from "./islands/Header/Cart/vtex.tsx";
import * as $Header_Cart_wake from "./islands/Header/Cart/wake.tsx";
import * as $Header_CopyCoupon from "./islands/Header/CopyCoupon.tsx";
import * as $Header_Drawers from "./islands/Header/Drawers.tsx";
import * as $Header_FreeShippingTopBar from "./islands/Header/FreeShippingTopBar.tsx";
import * as $Header_HeightHeader from "./islands/Header/HeightHeader.tsx";
import * as $Header_InformativeTopBar from "./islands/Header/InformativeTopBar.tsx";
import * as $Header_Searchbar from "./islands/Header/Searchbar.tsx";
import * as $HideShowFiltersDesktop from "./islands/HideShowFiltersDesktop.tsx";
import * as $LPSeoText from "./islands/LPSeoText.tsx";
import * as $Managedby from "./islands/Managedby.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $ProductBTGContent from "./islands/ProductBTGContent.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $ProductTabbedContent from "./islands/ProductTabbedContent.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $WishlistButton_vtex from "./islands/WishlistButton/vtex.tsx";
import * as $WishlistButton_wake from "./islands/WishlistButton/wake.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartButton/linx.tsx": $AddToCartButton_linx,
    "./islands/AddToCartButton/nuvemshop.tsx": $AddToCartButton_nuvemshop,
    "./islands/AddToCartButton/quantity.tsx": $AddToCartButton_quantity,
    "./islands/AddToCartButton/shopify.tsx": $AddToCartButton_shopify,
    "./islands/AddToCartButton/vnda.tsx": $AddToCartButton_vnda,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/AddToCartButton/vtexBTG.tsx": $AddToCartButton_vtexBTG,
    "./islands/AddToCartButton/vtexFloatingPDP.tsx":
      $AddToCartButton_vtexFloatingPDP,
    "./islands/AddToCartButton/vtexPDP.tsx": $AddToCartButton_vtexPDP,
    "./islands/AddToCartButton/wake.tsx": $AddToCartButton_wake,
    "./islands/BackToTop.tsx": $BackToTop,
    "./islands/ButtonCookies.tsx": $ButtonCookies,
    "./islands/CustomSort.tsx": $CustomSort,
    "./islands/EmptySearchParams.tsx": $EmptySearchParams,
    "./islands/FilterRangePrice.tsx": $FilterRangePrice,
    "./islands/Filters.tsx": $Filters,
    "./islands/FloatingBuyScroll.tsx": $FloatingBuyScroll,
    "./islands/FloatingDesktopHeaderPhytoSpa.tsx":
      $FloatingDesktopHeaderPhytoSpa,
    "./islands/FloatingMobileBar.tsx": $FloatingMobileBar,
    "./islands/Head.tsx": $Head,
    "./islands/Header/Buttons.tsx": $Header_Buttons,
    "./islands/Header/Cart/linx.tsx": $Header_Cart_linx,
    "./islands/Header/Cart/nuvemshop.tsx": $Header_Cart_nuvemshop,
    "./islands/Header/Cart/shopify.tsx": $Header_Cart_shopify,
    "./islands/Header/Cart/vnda.tsx": $Header_Cart_vnda,
    "./islands/Header/Cart/vtex.tsx": $Header_Cart_vtex,
    "./islands/Header/Cart/wake.tsx": $Header_Cart_wake,
    "./islands/Header/CopyCoupon.tsx": $Header_CopyCoupon,
    "./islands/Header/Drawers.tsx": $Header_Drawers,
    "./islands/Header/FreeShippingTopBar.tsx": $Header_FreeShippingTopBar,
    "./islands/Header/HeightHeader.tsx": $Header_HeightHeader,
    "./islands/Header/InformativeTopBar.tsx": $Header_InformativeTopBar,
    "./islands/Header/Searchbar.tsx": $Header_Searchbar,
    "./islands/HideShowFiltersDesktop.tsx": $HideShowFiltersDesktop,
    "./islands/LPSeoText.tsx": $LPSeoText,
    "./islands/Managedby.tsx": $Managedby,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/ProductBTGContent.tsx": $ProductBTGContent,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/ProductTabbedContent.tsx": $ProductTabbedContent,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/WishlistButton/vtex.tsx": $WishlistButton_vtex,
    "./islands/WishlistButton/wake.tsx": $WishlistButton_wake,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
